services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
       - DATABASE_URL=postgresql://user:password@db:5432/flask_db
       - FLASK_APP=app:create_app()  
       - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
    command: python -m flask run --host=0.0.0.0 --port=5000

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./backup_script.sh:/backup_script.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d flask_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: